version: "3.8"

services:
  # MySQL Database
  mysql:
    image: mysql:latest
    container_name: mysql
    networks:
      - networkmysql
    ports:
      - "3306:3306"  # Expose MySQL on port 3306
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rest_db
    volumes:
      - mysql-data:/var/lib/mysql # Persist MySQL data
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]  # Command to check if MySQL is healthy
      interval: 10s  # Interval between health checks
      retries: 5  # Number of retries before considering the service unhealthy
      start_period: 30s  # Initial delay before starting health checks
      timeout: 10s  # Timeout for each health check

  # Redis Service
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - networkmysql
    ports:
      - "6379:6379" # Expose Redis on port 6379
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]  # Command to check if Redis is healthy
      interval: 5s  # Interval between health checks
      timeout: 3s   # Timeout for each health check
      retries: 3    # Number of retries before considering the service unhealthy

  # Spring Boot backend
  rest-backend:
    image: kapilmika485/dockerassignment1:rest-backend-github-v4
    container_name: restContainer
    networks:
      - networkmysql
    user: "appuser"  # Explicitly set the user to "appuser" (not required if USER is already set in Dockerfile)
    ports:
      - "8383:8383" # Expose Spring Boot on port 8080
    depends_on:  # wait for running below container
      mysql: # web-app depends on db-service to be healthy
        condition: service_healthy  # Waits until db-service is healthy
      redis: # web-app depends on db-service to be healthy
        condition: service_healthy  # Waits until db-service is healthy
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB_NAME: rest_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  # Spring Boot frontend
  ui-application:
    image: kapilmika485/dockerassignment1:ui-github-v2
    container_name: uiContainer
    networks:
      - networkmysql
    user: "appuser"  # Explicitly set the user to "appuser" (not required if USER is already set in Dockerfile)
    ports:
      - "8484:8484"   # Expose the frontend on port 80
    depends_on:
      - rest-backend

# Define a volume for persisting MySQL data
volumes:
  mysql-data:
    driver: local

# Define the network for communication between services
networks:
  networkmysql:
