global:
  scrape_interval: 15s  # How often Prometheus scrapes the targets

scrape_configs:
  - job_name: 'microservices'
    metrics_path: 'actuator/prometheus'
    static_configs:
      - targets: ['uiContainer:8484']  # Replace with your microservice endpoint